version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - api  
  
  api:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
    image: api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - emongo  

  webapi:
    build:
      context: ./javaapi
      dockerfile: Dockerfile
    image: webapi
    container_name: webapi
    ports:
      - "9000:9000"
    depends_on:
      - emartdb  

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: emartdbpass  
      MYSQL_DATABASE: books
    ports:
      - "3306:3306" 

  emongo:
    image: mongo:4
    container_name: emongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: epoc
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - client  
      - api    
      - webapi    
