version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - api  
      - webapi
  
  api:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
    image: api
    container_name: api
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - emongo  
      - nginx

  webapi:
    build:
      context: ./javaapi
      dockerfile: Dockerfile
    image: webapi
    container_name: webapi
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      emartdb:
        condition: service_healthy  

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    environment:
      MYSQL_ROOT_PASSWORD: emartdbpass  
      MYSQL_DATABASE: books
    ports:
      - "3306:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      MONGO_INITDB_DATABASE: epoc
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"  
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
