pipeline {
    agent { label 'docker' }

    environment {
        SLACK_CHANNEL = '#stage'  
        ECR = 'my-ecr-url' 
        AWS_CRED = 'aws-cred' 
    }

    stages {

        stage('Docker Compose Up') {
            steps {
                script {
                    sh 'docker-compose -f docker-compose.yml up -d & echo "ECR URL: ${ECR}"'
                }
            }
            post {
                success {
                    slackSend(channel: "${SLACK_CHANNEL}", message: "Docker Compose containers are up! :white_check_mark:")
                }
                failure {
                    slackSend(channel: "${SLACK_CHANNEL}", message: "Docker Compose failed! :x:")
                }
            }
        }

        stage('Login to ECR') {
            steps {
                script {
                    withAWS(credentials: "${AWS_CRED}", region: 'us-east-1') {
                        sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR}'
                    }
                }
            }
        }

        stage('Push Images to ECR') {
            steps {
                script {
                    sh '''
                    docker tag db01 ${ECR}/db01:latest
                    docker tag app01 ${ECR}/app01:latest

                    docker push ${ECR}/db01:latest
                    docker push ${ECR}/app01:latest
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
