pipeline {
    agent { label 'docker' }

    environment {
        SLACK_CHANNEL = '#stage' // Specify your Slack channel
    }

    stages {

        stage('Docker Compose Up') {
            steps {
                script {
                    // Using a custom docker-compose file
                    sh 'docker-compose -f docker-compose.yml up -d'
                }
            }
            post {
                success {
                    slackSend(channel: "${SLACK_CHANNEL}", message: "Docker Compose containers are up! :white_check_mark:")
                }
                failure {
                    slackSend(channel: "${SLACK_CHANNEL}", message: "Docker Compose failed! :x:")
                }
            }
        }


    post {
        always {
            cleanWs()
        }
    }
}
