apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myproject-pvc
  labels:
    app: myproject-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 3Gi 
  storageClassName: default