apiVersion: v1
kind: Service
metadata:
  name: memcached-svc
  labels:
    app: memcached-svc
spec:
  selector:
    app: memcached-dep
  ports:
    - protocol: TCP
      port: 11211            
      targetPort: memcached-port
  type: ClusterIP