apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: rabbitmq-svc
spec:
  selector:
    app: rabbitmq-dep
  ports:
    - protocol: TCP
      port: 5672            
      targetPort: rabbitmq-port
    - protocol: TCP
      port: 15672           
      targetPort: rabbitmq-management-port
  type: ClusterIP