pipeline {
    agent any

    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }

    environment {
        SNAP_REPO = 'myproject-snapshot'
        CENTRAL_REPO = 'myproject-dep'
        NEXUS_GRP_REPO = 'myproject-group'
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'admin'
        SONAR_SERVER = 'sonarserver'
        SONAR_SCANNER = 'sonarscanner'
        NEXUS_CREDENTIALS_ID = 'nexuslogin'
        NEXUS_URL = '192.168.100.22:8081'
        RELEASE_REPO = 'myproject-release'
        GROUP_ID = 'QA'
        ARTIFACT_ID = 'vproapp'
        PACKAGING = 'war'
        VERSION = "1.0.${env.BUILD_ID}-${env.BUILD_TIMESTAMP}"
        registery_cred = ''
        appRegistry = ''
        vprofileregistry = ''
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'mvn -s settings.xml -DskipTests install'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'mvn -s settings.xml test'
                }
            }
        }

        stage('INTEGRATION TEST'){
            steps {
                sh 'mvn -s settings.xml verify -DskipUnitTests'
            }
        }
		
        stage ('CODE ANALYSIS WITH CHECKSTYLE'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
            post {
                success {
                    echo 'Generated Analysis Result'
                }
            }
        }

        stage('CODE ANALYSIS with SONARQUBE') {
          
		  environment {
             scannerHome = tool "${SONAR_SCANNER}"
          }

          steps {
            withSonarQubeEnv("${SONAR_SERVER}") {
               sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile-repo \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
            }

            timeout(time: 10, unit: 'MINUTES') {
               waitForQualityGate abortPipeline: true
            }
          }
        }

        // Additional stages...

        stage('Upload Artifact to Nexus') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUS_URL}",
                    groupId: "${GROUP_ID}",
                    version: "${VERSION}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_CREDENTIALS_ID}",
                    artifacts: [
                        [
                            artifactId: "${ARTIFACT_ID}",
                            classifier: '',
                            file: 'target/vprofile-v2.war',
                            type: "${PACKAGING}"
                        ]
                    ]
                )
            }
        }
    }
}
